### ISSUE TITLE
Minikube compatibility

### ISSUE THREAD

**Issue by NMichas** [jparklab/synology-csi#1]
Hello,

Is this driver suppose to work on minikube too? I get plenty of errors... I can post logs/errors if you wish.

My env:
Minikube 1.2.0 (MacOS 10.14.5, hyperkit driver)
Kubernetes v1.15.0 on Docker 18.09.6

**Comment by jparklab** [comment]
Does all pods fail to run? I expect synology-csi-node pods would fail on Mac since it depends on iscsi package on the image that is for ubuntu, and probably is not compatible with Mac.

**Comment by NMichas** [comment]
The problem with Minikube hyperkit driver seemed to be my firewall (Little Snitch) as it was not allowing  to fetch the Docker images. Strangely, I never got a firewall notification to allow/deny such connections (so they were silently dropped). I probably need to check pre-existing firewall rules to see what's going on here. 

I switched to Minikube on vmware driver which didn't seem to have any issues with my firewall. In this setup, here's my k8s status:
![Daemon_Sets_-_Kubernetes_Dashboard](https://user-images.githubusercontent.com/2218296/61931821-72548480-af8a-11e9-8667-752f3a6ecfa1.png)
![Pods_-_Kubernetes_Dashboard](https://user-images.githubusercontent.com/2218296/61931838-7ed8dd00-af8a-11e9-9fe6-89779752d712.png)
![Stateful_Sets_-_Kubernetes_Dashboard](https://user-images.githubusercontent.com/2218296/61931853-88624500-af8a-11e9-9d48-d5db49d37e6f.png)

Let me know if I can provide any additional logs/info, I'd be glad to help you debug this if you can make it work.

p.s. It's a pity Synology doesn't lend a hand on this project (or at least provide their own CSI driver), especially considering they have an "enterprise" series of products.

**Comment by jparklab** [comment]
Mac does not have integrated ISCSI initiator(https://discussions.apple.com/thread/6114624). The driver requires iscsi initiator installed on the host OS in order to mount the volume onto the host, and therefore, it won't work on Mac.

**Comment by jparklab** [comment]
ps. Yes, I wish they at least open their spec on the APIs. It would make a lot easier to make open source projects that use their APIs
