### ISSUE TITLE
Self-signed certificate for Synology DSM

### ISSUE THREAD

**Issue by dannyyy** [jparklab/synology-csi#13]
I tried to setup the CSI driver on my single-node (microk8s.io) kubernetes cluster which is based on Ubuntu 19.10. 

To fit the my security needs I changed the `port` and enabled `sslVerify`. But this raises the issue, that the self-signed certificate from the Synology NAS could not be verified. 
I added the CA certificate to `/usr/local/share/ca-certificates/` and executed `update-ca-certificates` which added the new CA certificate. To be sure I rebooted the whole single-node cluster.

But even with this, the driver is still complaining. IP and password has been replaced.
```
$ kubectl logs synology-csi-attacher-0 -n synology-csi -c csi-plugin
I0104 11:51:25.024914       1 driver.go:66] Driver: csi.synology.com
I0104 11:51:25.025339       1 driver.go:77] Use synology: https://1.1.1.1:5001/webapi
I0104 11:51:25.026033       1 session.go:128] Logging in via https://1.1.1.1:5001/webapi/auth.cgi?account=k8s&api=SYNO.API.Auth&format=sid&method=login&passwd=xxx&session=Core&version=2
I0104 11:51:25.223472       1 driver.go:82] Failed to login: Get https://1.1.1.1:5001/webapi/auth.cgi?account=k8s&api=SYNO.API.Auth&format=sid&method=login&passwd=xxx&session=Core&version=2: x509: certificate signed by unknown authority
Failed to create driver: Get https://1.1.1.1:5001/webapi/auth.cgi?account=k8s&api=SYNO.API.Auth&format=sid&method=login&passwd=xxx&session=Core&version=2: x509: certificate signed by unknown authority
```

Do somebody know how to solve this?

**Comment by jparklab** [comment]
@dannyyy  The certificate also needs to be added to the kubernetes pods. I updated readme with an example on how to add certificate to the pods. 
Give it a try and let me know if it works.
