### ISSUE TITLE
Reference Issue

### ISSUE THREAD

**Issue by reski-rukmantiyo** [jparklab/synology-csi#42]
Hi @jparklab ,

Thanks for your great csi libs for kubernetes. I try to using this lib for v1.18
several things that i dont understand
1. in syno-config.yml
`deviceId: <device-id>      # Optional. Only for versions 6 and above. If not set, DEVICE_ID environment var is read.
deviceName: <name>         # Optional. Only for versions 6 and above.`
- how to now which version that i'm using
- what is deviceId and devinceName and how to look value for this

2. when i try to debug
`csc controller create-volume \
  --req-bytes 2147483648 \
  -e tcp://127.0.0.1:10000 \
  test-volume
"8.1" 2147483648 "iqn"="iqn.2000-01.com.synology:kube-csi-test-volume" "mappingIndex"="1" "targetID"="8"`

- what is mappingIndex and targetId ? and how to look value for this?

Help very appreciate. Thanks

**Comment by jparklab** [comment]
Hi, @reski-rukmantiyo 

deviceId and deviceName are optional and they are not currently used. You do not need to specify them.
which version you can use depends on the NAS model you have. 
Unfortunately, there is no good documentation from Synology to tell which version your NAS support. You'd need to try different versions and see if it works for you.

mappingIndex and targetId are numbers returns by Synology APIs and it would be useful when you query the volume using Synology APIs. You can find them in https://github.com/jparklab/synology-csi/blob/master/pkg/synology/api/iscsi/target.go
